# Generated by Django 3.2.8 on 2021-10-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidClosed',
            field=models.BooleanField(default=False),
        ),
    ]
