# Generated by Django 2.2.10 on 2021-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210921_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.TextField(max_length=200, null=True, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(max_length=200, null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(default='quidroo', max_length=50, verbose_name='User role'),
        ),
    ]
