# Generated by Django 3.2.8 on 2021-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bid_bidclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='winning_buyer_id',
            field=models.CharField(default='0', max_length=500, verbose_name='Winning Buyer/Investor ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=200, null=True, verbose_name='Profile Pics'),
        ),
    ]
