# Generated by Django 3.2.8 on 2021-11-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211103_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(default='395f2c4c0948911df0461865e9a5fc06ad8c537cfc894224fc748fa4a1b5211f', max_length=1000, verbose_name='Paystack Transaction Reference'),
        ),
    ]
