# Generated by Django 3.2.8 on 2021-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Bidder ID'),
        ),
    ]
