# Generated by Django 3.2.8 on 2021-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bid_bidder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='bvn',
            field=models.CharField(max_length=200, null=True, verbose_name='BVN'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='cac_no',
            field=models.CharField(blank=True, max_length=300, verbose_name='CAC No'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='nin',
            field=models.CharField(max_length=105, null=True, verbose_name='NIN'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='tin',
            field=models.CharField(max_length=105, null=True, verbose_name='TIN'),
        ),
    ]
