# Generated by Django 2.2.10 on 2021-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210926_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='none', max_length=500, unique=True, verbose_name='Type of Transaction'),
        ),
    ]
