# Generated by Django 2.2.10 on 2021-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='none', max_length=500, verbose_name='Type of Transaction'),
        ),
    ]
