# Generated by Django 3.2.8 on 2021-11-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
