# Generated by Django 3.2.7 on 2021-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210930_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_id',
            field=models.CharField(max_length=500, verbose_name='Reciever'),
        ),
    ]
