# Generated by Django 2.2.10 on 2021-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210928_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_id',
            field=models.CharField(max_length=500, verbose_name='Reciever'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.CharField(max_length=500, verbose_name='Sender'),
        ),
    ]
