# Generated by Django 3.2.8 on 2021-11-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paidByQuidroo',
            field=models.BooleanField(default=False),
        ),
    ]
