# Generated by Django 3.2.7 on 2021-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_transaction_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.CharField(max_length=500, verbose_name='Sender'),
        ),
    ]
