# Generated by Django 2.2.10 on 2021-10-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210928_0831'),
        ('app', '0010_alter_transaction_sender_id'),
    ]

    operations = [
    ]
