# Generated by Django 3.2.8 on 2021-12-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_transaction_paidbyquidroo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fiat_equivalent',
            field=models.FloatField(blank=True, max_length=1000, verbose_name='Fiat Equivalent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_balance',
            field=models.FloatField(blank=True, max_length=1000, verbose_name='Token Amount Transacted'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_note',
            field=models.CharField(max_length=3000, null=True, verbose_name='Transaction note'),
        ),
    ]
