# Generated by Django 3.2.8 on 2021-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_url',
            field=models.FileField(unique=True, upload_to='invoices', verbose_name='Invoice Doc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.FileField(null=True, upload_to='avatars', verbose_name='Profile Pics'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='bank_statement',
            field=models.FileField(null=True, upload_to='cacs', verbose_name='Bank Statement'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='cac_certificate',
            field=models.FileField(upload_to='cacs', verbose_name='CAC Certificate'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='user_Idcard',
            field=models.FileField(blank=True, upload_to='idcards', verbose_name='ID Card'),
        ),
    ]
