# Generated by Django 3.2.8 on 2021-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211207_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.TextField(default='2', max_length=200, verbose_name='How many years in Business?'),
        ),
    ]
