# Generated by Django 2.2.10 on 2021-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211001_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='muxed_acct',
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.TextField(default=0.1, max_length=200, null=True, verbose_name='Quidroo Credit Score'),
        ),
    ]
