# Generated by Django 2.2.10 on 2021-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211008_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='seller_id',
            field=models.CharField(max_length=500, verbose_name='Seller ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_email',
            field=models.EmailField(max_length=90, verbose_name='Vendor Email'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Vendor Phone'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='winning_buyer_id',
            field=models.CharField(max_length=500, verbose_name='Winning Buyer/Investor ID'),
        ),
    ]
