# Generated by Django 2.2.10 on 2021-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211009_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='Date Invoice is Due'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_state',
            field=models.IntegerField(default=0, verbose_name='Invoice State'),
        ),
    ]
