# Generated by Django 2.2.10 on 2021-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211010_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(verbose_name='Date Invoice is Due'),
        ),
    ]
