# Generated by Django 2.2.10 on 2021-10-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211010_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='Vendor Name')),
                ('user_id', models.TextField(default=0.09, max_length=20, verbose_name='Vendor Credit score')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'RecentActivty_table',
            },
        ),
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Vendor Name')),
                ('credit_score', models.TextField(default=0.09, max_length=20, verbose_name='Vendor Credit score')),
                ('isVerified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Vendor_table',
            },
        ),
    ]
