# Generated by Django 2.2.10 on 2021-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_recentactivity_vendorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='tin',
            field=models.CharField(max_length=105, null=True, unique=True, verbose_name='TIN'),
        ),
    ]
