# Generated by Django 2.2.10 on 2021-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_verification_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verification',
            name='awaiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
