# Generated by Django 2.2.10 on 2021-10-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211017_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='approved',
        ),
    ]
